//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ATLANTISEntities : DbContext
    {
        public ATLANTISEntities()
            : base("name=ATLANTISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgenteAduanal> AgenteAduanal { get; set; }
        public virtual DbSet<BLEmbarque> BLEmbarque { get; set; }
        public virtual DbSet<Buque> Buque { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<ClienteTarifaSer> ClienteTarifaSer { get; set; }
        public virtual DbSet<Componente> Componente { get; set; }
        public virtual DbSet<Condicion> Condicion { get; set; }
        public virtual DbSet<ConductorUndTrans> ConductorUndTrans { get; set; }
        public virtual DbSet<Contenedor> Contenedor { get; set; }
        public virtual DbSet<ContenedorEIR> ContenedorEIR { get; set; }
        public virtual DbSet<ContenedorMovimiento> ContenedorMovimiento { get; set; }
        public virtual DbSet<Daño> Daño { get; set; }
        public virtual DbSet<Demora> Demora { get; set; }
        public virtual DbSet<DemoraContenedor> DemoraContenedor { get; set; }
        public virtual DbSet<DemoraTarifa> DemoraTarifa { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<EmpresaCuentaBancaria> EmpresaCuentaBancaria { get; set; }
        public virtual DbSet<EmpresaServicio> EmpresaServicio { get; set; }
        public virtual DbSet<EmpresaTransporte> EmpresaTransporte { get; set; }
        public virtual DbSet<EstatusContenedor> EstatusContenedor { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<FacturaServicio> FacturaServicio { get; set; }
        public virtual DbSet<GrupoOpcion> GrupoOpcion { get; set; }
        public virtual DbSet<Itinerario> Itinerario { get; set; }
        public virtual DbSet<ItinerarioContenedor> ItinerarioContenedor { get; set; }
        public virtual DbSet<ItinerarioEmbContenedor> ItinerarioEmbContenedor { get; set; }
        public virtual DbSet<ItinerarioUbicacion> ItinerarioUbicacion { get; set; }
        public virtual DbSet<Lado> Lado { get; set; }
        public virtual DbSet<LineaBuque> LineaBuque { get; set; }
        public virtual DbSet<LineaMaritima> LineaMaritima { get; set; }
        public virtual DbSet<LineaPool> LineaPool { get; set; }
        public virtual DbSet<MetodoReparacion> MetodoReparacion { get; set; }
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<Oficina> Oficina { get; set; }
        public virtual DbSet<Opcion> Opcion { get; set; }
        public virtual DbSet<OpcionMensajeUsuario> OpcionMensajeUsuario { get; set; }
        public virtual DbSet<OrdenReparacion> OrdenReparacion { get; set; }
        public virtual DbSet<OrdenRepComponente> OrdenRepComponente { get; set; }
        public virtual DbSet<Preliquidacion> Preliquidacion { get; set; }
        public virtual DbSet<PreliquidacionContenedor> PreliquidacionContenedor { get; set; }
        public virtual DbSet<PreliquidacionEstatus> PreliquidacionEstatus { get; set; }
        public virtual DbSet<PreliquidacionServicio> PreliquidacionServicio { get; set; }
        public virtual DbSet<Procedencia> Procedencia { get; set; }
        public virtual DbSet<Puerto> Puerto { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<ReservaContenedor> ReservaContenedor { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<ServicioTarifa> ServicioTarifa { get; set; }
        public virtual DbSet<TasaCambio> TasaCambio { get; set; }
        public virtual DbSet<TasaCambioMov> TasaCambioMov { get; set; }
        public virtual DbSet<TipoContenedor> TipoContenedor { get; set; }
        public virtual DbSet<TipoEIR> TipoEIR { get; set; }
        public virtual DbSet<TipoISOContenedor> TipoISOContenedor { get; set; }
        public virtual DbSet<TipoMensajeUsuario> TipoMensajeUsuario { get; set; }
        public virtual DbSet<TipoPreliquidacion> TipoPreliquidacion { get; set; }
        public virtual DbSet<TipoTamaño> TipoTamaño { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
        public virtual DbSet<UnidadTransporte> UnidadTransporte { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioModulo> UsuarioModulo { get; set; }
        public virtual DbSet<UsuarioOpcion> UsuarioOpcion { get; set; }
        public virtual DbSet<OrdenRepImagen> OrdenRepImagen { get; set; }
    }
}
