//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteTarifaSer
    {
        public int IdTarifaSerCliente { get; set; }
        public int IdCliente { get; set; }
        public int IdServicio { get; set; }
        public int IdEmpresa { get; set; }
        public int IdLinea { get; set; }
        public int TipoServicio { get; set; }
        public double ValorTarifaSerCliente { get; set; }
        public Nullable<double> NuevaTarifaCliente { get; set; }
        public Nullable<System.DateTime> FechaDesdeTarifaCliente { get; set; }
    }
}
