//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contenedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contenedor()
        {
            this.ContenedorEIR = new HashSet<ContenedorEIR>();
            this.ContenedorMovimiento = new HashSet<ContenedorMovimiento>();
            this.DemoraContenedor = new HashSet<DemoraContenedor>();
            this.ItinerarioEmbContenedor = new HashSet<ItinerarioEmbContenedor>();
            this.ItinerarioContenedor = new HashSet<ItinerarioContenedor>();
            this.ReservaContenedor = new HashSet<ReservaContenedor>();
        }
    
        public int IdContenedor { get; set; }
        public string SiglasContenedor { get; set; }
        public int TipoContenedor { get; set; }
        public short TamañoContenedor { get; set; }
        public Nullable<int> CondicionContenedor { get; set; }
        public Nullable<int> LineaContenedor { get; set; }
        public bool PuertosCriticosContenedor { get; set; }
        public bool SiglasUniversalesContenedor { get; set; }
        public Nullable<int> EstatusContenedor { get; set; }
        public Nullable<int> EventoContenedor { get; set; }
        public string CodigoContenedor { get; set; }
        public Nullable<bool> ReservadoContenedor { get; set; }
        public Nullable<int> UbicacionContenedor { get; set; }
    
        public virtual Condicion Condicion { get; set; }
        public virtual EstatusContenedor EstatusContenedor1 { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual LineaMaritima LineaMaritima { get; set; }
        public virtual TipoContenedor TipoContenedor1 { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContenedorEIR> ContenedorEIR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContenedorMovimiento> ContenedorMovimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemoraContenedor> DemoraContenedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItinerarioEmbContenedor> ItinerarioEmbContenedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItinerarioContenedor> ItinerarioContenedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaContenedor> ReservaContenedor { get; set; }
    }
}
