//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContenedorEIR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContenedorEIR()
        {
            this.OrdenReparacion = new HashSet<OrdenReparacion>();
        }
    
        public int IdContenedorEIR { get; set; }
        public Nullable<int> IdContenedor { get; set; }
        public Nullable<int> NroEIR { get; set; }
        public Nullable<System.DateTime> FechaEIR { get; set; }
        public int TipoEIR { get; set; }
        public int NroExpEIR { get; set; }
        public Nullable<int> NroEIRFullI { get; set; }
        public Nullable<System.DateTime> FechaEIRFullI { get; set; }
        public Nullable<int> CondicionEIR { get; set; }
        public Nullable<int> UbicacionEIR { get; set; }
        public Nullable<int> AgenteAduanalEIR { get; set; }
        public Nullable<int> UnidadTransporteEIR { get; set; }
        public Nullable<int> ConductorUnidadEIR { get; set; }
        public string ObservacionesEIR { get; set; }
        public string RazonAnulacionEIR { get; set; }
        public int UsuarioEIR { get; set; }
        public Nullable<bool> AnuladaEIR { get; set; }
        public Nullable<int> EventoEIR { get; set; }
        public Nullable<int> EstatusEIR { get; set; }
        public Nullable<bool> ProcesadoediEIR { get; set; }
        public Nullable<bool> ReingresoEIR { get; set; }
        public Nullable<bool> ImpresaEIR { get; set; }
        public Nullable<int> ProcedenciaEIR { get; set; }
    
        public virtual AgenteAduanal AgenteAduanal { get; set; }
        public virtual Condicion Condicion { get; set; }
        public virtual ConductorUndTrans ConductorUndTrans { get; set; }
        public virtual Contenedor Contenedor { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual TipoEIR TipoEIR1 { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        public virtual UnidadTransporte UnidadTransporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenReparacion> OrdenReparacion { get; set; }
    }
}
