//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContenedorMovimiento
    {
        public int IdContenedorMov { get; set; }
        public int IdContenedor { get; set; }
        public int ItinerarioContenedorMov { get; set; }
        public System.DateTime FechaContenedorMov { get; set; }
        public int EventoContenedorMov { get; set; }
        public Nullable<int> EstatusContenedorMov { get; set; }
        public Nullable<int> NroExpContenedorMov { get; set; }
        public Nullable<int> UbicacionContenedorMov { get; set; }
    
        public virtual Contenedor Contenedor { get; set; }
        public virtual EstatusContenedor EstatusContenedor { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual Itinerario Itinerario { get; set; }
    }
}
