//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemoraContenedor
    {
        public int IdDemoraContenedor { get; set; }
        public int IdDemora { get; set; }
        public int IdContenedor { get; set; }
        public int CantidadDemoraContenedor { get; set; }
        public double PrecioDemoraContenedorUSD { get; set; }
        public double TotalDemoraContenedorUSD { get; set; }
        public double PrecioDemoraContenedorBS { get; set; }
        public double TotalDemoraContenedorBS { get; set; }
        public bool FacturadoDemoraContenedor { get; set; }
    
        public virtual Contenedor Contenedor { get; set; }
        public virtual Demora Demora { get; set; }
    }
}
