//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItinerarioEmbContenedor
    {
        public int IdEmbContenedor { get; set; }
        public int ItinerarioEmbarque { get; set; }
        public int IdContenedor { get; set; }
        public string BahiaEmbContenedor { get; set; }
        public string SlotEmbContenedor { get; set; }
        public string Precinto1EmbContenedor { get; set; }
        public string Precinto2EmbContenedor { get; set; }
        public Nullable<double> PesoEmbContenedor { get; set; }
        public Nullable<bool> VerificaEmbContenedor { get; set; }
        public Nullable<bool> ProcesadoEmbContenedor { get; set; }
        public string Descripcion1EmbContenedor { get; set; }
        public string Descripcion2EmbContenedor { get; set; }
        public string Descripcion3EmbContenedor { get; set; }
        public string Descripcion4EmbContenedor { get; set; }
        public string TemperaturaEmbContenedor { get; set; }
        public string RngTempEmbContenedor { get; set; }
        public string MatPeligrosoEmbContenedor { get; set; }
    
        public virtual Contenedor Contenedor { get; set; }
        public virtual Itinerario Itinerario { get; set; }
    }
}
