//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Itinerario()
        {
            this.BLEmbarque = new HashSet<BLEmbarque>();
            this.ContenedorMovimiento = new HashSet<ContenedorMovimiento>();
            this.ItinerarioContenedor = new HashSet<ItinerarioContenedor>();
            this.ItinerarioEmbContenedor = new HashSet<ItinerarioEmbContenedor>();
            this.ItinerarioUbicacion = new HashSet<ItinerarioUbicacion>();
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int IdItinerario { get; set; }
        public Nullable<int> IdBuqueItinerario { get; set; }
        public Nullable<int> IdLineaItinerario { get; set; }
        public System.DateTime FechaHoraLlegadaItinerario { get; set; }
        public System.DateTime FechaHoraSalidaItinerario { get; set; }
        public string NroViajeLlegadaItinerario { get; set; }
        public string NroViajeSalidaItinerario { get; set; }
        public string NroSiduneaItinerario { get; set; }
        public int NroExpediente { get; set; }
        public Nullable<int> UsuarioItinerario { get; set; }
        public Nullable<bool> GeneradoEDIItinerario { get; set; }
        public Nullable<bool> GeneradoEDIEmbarqueF { get; set; }
        public Nullable<bool> GeneradoEDIEmbarqueV { get; set; }
        public Nullable<int> PuertoEscalaItinerario { get; set; }
        public Nullable<System.DateTime> FechaEstimadaLlegadaItinerario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLEmbarque> BLEmbarque { get; set; }
        public virtual Buque Buque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContenedorMovimiento> ContenedorMovimiento { get; set; }
        public virtual LineaMaritima LineaMaritima { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItinerarioContenedor> ItinerarioContenedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItinerarioEmbContenedor> ItinerarioEmbContenedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItinerarioUbicacion> ItinerarioUbicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
