//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItinerarioUbicacion
    {
        public int IdItinearioUbicacion { get; set; }
        public int IdItinerario { get; set; }
        public int IdUbicacion { get; set; }
        public Nullable<int> NroExpediente { get; set; }
        public int CantidadContenedoresItinearioUbicacion { get; set; }
    
        public virtual Itinerario Itinerario { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
    }
}
