//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaBuque
    {
        public int IdLineaBuque { get; set; }
        public int IdLineaMaritima { get; set; }
        public int IdBuque { get; set; }
    
        public virtual Buque Buque { get; set; }
        public virtual LineaMaritima LineaMaritima { get; set; }
    }
}
