//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opcion()
        {
            this.OpcionMensajeUsuario = new HashSet<OpcionMensajeUsuario>();
            this.UsuarioOpcion = new HashSet<UsuarioOpcion>();
        }
    
        public int IdOpcion { get; set; }
        public string DescripcionOpcion { get; set; }
        public string IconoOpcion { get; set; }
        public string UrlOpcion { get; set; }
        public int ModuloOpcion { get; set; }
        public Nullable<int> GrupoOpcion { get; set; }
        public Nullable<short> DocPendientesOpcion { get; set; }
    
        public virtual GrupoOpcion GrupoOpcion1 { get; set; }
        public virtual Modulo Modulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpcionMensajeUsuario> OpcionMensajeUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioOpcion> UsuarioOpcion { get; set; }
    }
}
