//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpcionMensajeUsuario
    {
        public int IdMensajeUsuario { get; set; }
        public int IdOpcion { get; set; }
        public int IdUsuario { get; set; }
        public string DescripcionMensajeUsuario { get; set; }
        public int TipoMensajeUsuario { get; set; }
    
        public virtual Opcion Opcion { get; set; }
        public virtual TipoMensajeUsuario TipoMensajeUsuario1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
