//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenReparacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenReparacion()
        {
            this.OrdenRepComponente = new HashSet<OrdenRepComponente>();
        }
    
        public int IdOrdenRep { get; set; }
        public System.DateTime FechaOrdenRep { get; set; }
        public int IdContenedorEIR { get; set; }
        public Nullable<System.DateTime> FechaIngTallerOrdenRep { get; set; }
        public Nullable<System.DateTime> FechaInicioOrdenRep { get; set; }
        public Nullable<System.DateTime> FechaFinalOrdenRep { get; set; }
        public string ObservacionOrdenRep { get; set; }
        public Nullable<bool> TerminadaOrdRep { get; set; }
        public Nullable<bool> AnuladaOrdRep { get; set; }
        public Nullable<System.DateTime> FechaFinalDefOrdRep { get; set; }
        public Nullable<bool> DañoenPatioOrdRep { get; set; }
    
        public virtual ContenedorEIR ContenedorEIR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenRepComponente> OrdenRepComponente { get; set; }
    }
}
