//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preliquidacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preliquidacion()
        {
            this.PreliquidacionContenedor = new HashSet<PreliquidacionContenedor>();
            this.PreliquidacionServicio = new HashSet<PreliquidacionServicio>();
        }
    
        public int IdPreliquidacion { get; set; }
        public int NroPreliquidacion { get; set; }
        public System.DateTime FechaPreliquidacion { get; set; }
        public int ClientePreliquidacion { get; set; }
        public int EmpresaPreliquidacion { get; set; }
        public Nullable<int> BLPreliquidacion { get; set; }
        public Nullable<int> TasaCambioBLPreliquidacion { get; set; }
        public Nullable<double> SubTotalPreliquidacionBS { get; set; }
        public Nullable<double> SubTotalPreliquidacionUSD { get; set; }
        public Nullable<double> MontoIvaPreliquidacionBS { get; set; }
        public Nullable<double> MontoIvaPreliquidacionUDS { get; set; }
        public Nullable<double> TotalPreliquidacionBS { get; set; }
        public Nullable<double> TotalPreliquidacionUSD { get; set; }
        public string ObservacionPreliquidacion { get; set; }
        public Nullable<int> UsuarioPreliquidacion { get; set; }
        public Nullable<int> EstatusPreliquidacion { get; set; }
        public Nullable<int> TipoPreliquidacion { get; set; }
        public Nullable<int> ReservaPreliquidacion { get; set; }
        public Nullable<int> AgenteAduanalPreliquidacion { get; set; }
        public string BuquePreliquidacion { get; set; }
        public Nullable<System.DateTime> FechaViajePreliquidacion { get; set; }
        public string NroViajePreliquidacion { get; set; }
        public Nullable<int> CorrelativoPreliquidacion { get; set; }
        public string NroSolvenciaPreliquidacion { get; set; }
        public Nullable<System.DateTime> FechaHastaSolvenciaPreliquidacion { get; set; }
        public Nullable<bool> SolventePreliquidacion { get; set; }
        public string NroFacturaPreliquidacion { get; set; }
        public Nullable<System.DateTime> FechaFacturaPreliquidacion { get; set; }
        public Nullable<double> ValorTasaPreliquidacion { get; set; }
    
        public virtual BLEmbarque BLEmbarque { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual PreliquidacionEstatus PreliquidacionEstatus { get; set; }
        public virtual TasaCambio TasaCambio { get; set; }
        public virtual TipoPreliquidacion TipoPreliquidacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreliquidacionContenedor> PreliquidacionContenedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreliquidacionServicio> PreliquidacionServicio { get; set; }
    }
}
