//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaContenedor
    {
        public int IdReservaContenedor { get; set; }
        public int IdReserva { get; set; }
        public int IdContenedor { get; set; }
    
        public virtual Contenedor Contenedor { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
