//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio()
        {
            this.EmpresaServicio = new HashSet<EmpresaServicio>();
            this.PreliquidacionServicio = new HashSet<PreliquidacionServicio>();
            this.ServicioTarifa = new HashSet<ServicioTarifa>();
        }
    
        public int IdServicio { get; set; }
        public string CodigoServicio { get; set; }
        public string DescripcionServicio { get; set; }
        public Nullable<bool> ControlServicio { get; set; }
        public Nullable<bool> SeleccionRapidaImpServicio { get; set; }
        public Nullable<bool> SeleccionRapidaExpServicio { get; set; }
        public Nullable<bool> SeleccionRapidaOpeServicio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaServicio> EmpresaServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreliquidacionServicio> PreliquidacionServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicioTarifa> ServicioTarifa { get; set; }
    }
}
