//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioTarifa
    {
        public int IdServicioTarifa { get; set; }
        public int IdServicio { get; set; }
        public int IdEmpresa { get; set; }
        public int IdLinea { get; set; }
        public int TipoServicio { get; set; }
        public double ValorTarifa { get; set; }
        public Nullable<double> NuevaTarifa { get; set; }
        public Nullable<System.DateTime> FechaDesdeTarifa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual LineaMaritima LineaMaritima { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual TipoPreliquidacion TipoPreliquidacion { get; set; }
    }
}
