//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTamaño
    {
        public int IdTipoTamaño { get; set; }
        public int TipoContenedor { get; set; }
        public short TamañoTipoContenedor { get; set; }
        public Nullable<short> AltoPieTipoTamaño { get; set; }
        public Nullable<short> AltoPulgadaTipoTamaño { get; set; }
        public Nullable<double> PesoTipoTamaño { get; set; }
    
        public virtual TipoContenedor TipoContenedor1 { get; set; }
    }
}
