//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoISOContenedor
    {
        public int IdTipoISOContenedor { get; set; }
        public string CodigoISOContenedor { get; set; }
        public string DescripcionISOContenedor { get; set; }
        public string TamanoISOContenedor { get; set; }
        public string AbreviaturaISOContenedor { get; set; }
    }
}
