//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadTransporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnidadTransporte()
        {
            this.ContenedorEIR = new HashSet<ContenedorEIR>();
        }
    
        public int IdUnidadTransporte { get; set; }
        public string DescripcionUnidadTransporte { get; set; }
        public string PlacaUnidadTransporte { get; set; }
        public int EmpresaUnidadTransporte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContenedorEIR> ContenedorEIR { get; set; }
        public virtual EmpresaTransporte EmpresaTransporte { get; set; }
    }
}
