//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioModulo
    {
        public int IdUsuarioModulo { get; set; }
        public int IdUsuario { get; set; }
        public int IdModulo { get; set; }
        public Nullable<int> IdRolUsuarioModulo { get; set; }
    
        public virtual Modulo Modulo { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
