//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVeconinter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Itinerario = new HashSet<Itinerario>();
            this.OpcionMensajeUsuario = new HashSet<OpcionMensajeUsuario>();
            this.Reserva = new HashSet<Reserva>();
            this.UsuarioModulo = new HashSet<UsuarioModulo>();
            this.UsuarioOpcion = new HashSet<UsuarioOpcion>();
        }
    
        public int IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public Nullable<int> DepartamentoUsuario { get; set; }
        public string LoginUsuario { get; set; }
        public string PasswordUsuario { get; set; }
        public string FotoUsuario { get; set; }
        public Nullable<bool> CambioClaveUsuario { get; set; }
        public Nullable<int> OficinaUsuario { get; set; }
        public Nullable<System.DateTime> FechaCambioPassword { get; set; }
        public Nullable<bool> InactivoUsuario { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itinerario> Itinerario { get; set; }
        public virtual Oficina Oficina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpcionMensajeUsuario> OpcionMensajeUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioModulo> UsuarioModulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioOpcion> UsuarioOpcion { get; set; }
    }
}
